"""
LLM (Large Language Model) Service.
Responsible for communicating with the Groq API to generate answers based on 
the context retrieved from our travel database.
"""
import os
from groq import Groq, RateLimitError, AuthenticationError, APIConnectionError, APIStatusError, APITimeoutError, GroqError
from dotenv import load_dotenv

# Load environment variables from the .env file (e.g., GROQ_API_KEY)
load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")

# Initialize the Groq client if the API key is present
client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None

# The SYSTEM_PROMPT is crucial. It acts as the brain/rules engine for the AI.
# It enforces strict formatting rules and explicitly forbids hallucination.
# You can modify the length and tone of the AI's responses by changing these instructions.
SYSTEM_PROMPT = """You are a highly professional Tripigo Tales Travel Assistant. You must answer ONLY using the provided Tripigo knowledge base context.

CRITICAL INSTRUCTIONS:
1. NEVER hallucinate or invent information. If the answer is not in the provided context, you MUST return exactly this phrase and nothing else:
I couldn't find that information in Tripigo's travel database.
2. NEVER invent: Cancellation policies, refund policies, payment methods, discounts, group offers, contact details, or package customizations unless they are explicitly present in the retrieved context.
3. FORMATTING: Always return beautifully formatted Markdown. Use headings (`##`, `###`), **bold text**, bullet points, numbered lists, and tables where appropriate. Never return large walls of text. Ensure there is spacing between sections.

SPECIFIC FORMATS:

Package Recommendations (if multiple, rank from best match to least match):
## Recommended Packages

### **[Package Name]**
- Destination: [Destination]
- Duration: [Duration]
- Price: **[Price]**
- Highlights: [Highlights]

### Why This Matches Your Requirements
[Short explanation]

Package Comparison:
## Package Comparison
| Package | Duration | Price | Best For |
|----------|----------|----------|----------|
| ... | ... | ... | ... |

Contact Information:
## Contact Information
📍 Location: [Location]
📞 Phone: [Phone]
📧 Email: [Email]

Customer Reviews:
## Customer Reviews
### ⭐ [Customer Name]
[Review text]

Always ensure package names are **bold**, prices are **highlighted/bold**, and durations are shown.
"""

def generate_answer(query: str, contexts: list[str]) -> str:
    """
    Generates an answer to the user's query strictly using the provided contexts.
    
    Args:
        query (str): The question asked by the user.
        contexts (list[str]): The relevant text snippets retrieved from the database.
        
    Returns:
        str: The Markdown-formatted answer generated by the Groq LLM.
    """
    if not client:
        return "Error: GROQ_API_KEY not configured in .env file."
        
    # Build the strict prompt containing the knowledge base and the user's question
    prompt = "Knowledge Base:\n"
    for ctx in contexts:
        prompt += f"{ctx}\n\n"
    prompt += f"User Question: {query}\n"
    prompt += "Answer:"
    
    try:
        # Request a chat completion from the Groq API
        chat_completion = client.chat.completions.create(
            messages=[
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            # We use the LLaMA 3.1 8B Instant model because it is incredibly fast 
            # and highly capable for RAG (Retrieval-Augmented Generation) tasks.
            model="llama-3.1-8b-instant",
            temperature=0.3, # Low temperature ensures the model remains factual and doesn't guess
            max_tokens=1024, # Maximum length of the generated response
        )
        choice = chat_completion.choices[0]
        
        # Handle cases where the response hit the maximum token limit
        if choice.finish_reason == 'length':
            return "Error: The response was cut off because it exceeded the maximum token limit. Please try asking a more specific question."
            
        return choice.message.content
        
    # Comprehensive error handling to gracefully handle any API issues
    except RateLimitError as e:
        return f"Error: Rate limit exceeded. Please wait a moment before trying again. ({str(e)})"
    except AuthenticationError as e:
        return f"Error: Authentication failed. Please check if your GROQ_API_KEY is valid. ({str(e)})"
    except APIConnectionError as e:
        return f"Error: Could not connect to Groq API. Please check your internet connection. ({str(e)})"
    except APITimeoutError as e:
        return f"Error: The request to Groq API timed out. Please try again later. ({str(e)})"
    except APIStatusError as e:
        return f"Error: Groq API returned an error status code. ({str(e)})"
    except GroqError as e:
        return f"Error: An issue occurred with the Groq API. ({str(e)})"
    except Exception as e:
        return f"Error: An unexpected error occurred: {str(e)}"
